server:
    port: 10080

# SPRING PROFILES
spring:
    # HTTP ENCODING
    http:
        encoding.charset: UTF-8
        encoding.enable: true
        encoding.force: true
        multipart.maxFileSize: 100MB
        multipart.maxRequestSize: 100MB

    activemq:
      broker-url: tcp://192.168.1.201:61616
      user: admin
      password: admin


queueName: com.osplans.activeMq