spring:
  application:
    name: spring-demo
  datasource:
    url: jdbc:mysql://localhost:3306/cup3014
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  freemarker:
    suffix: .html

server:
  port: 10090

